development:
  # PostgreSQL
  POSTGRESQL_USERNAME: <%= ENV['POSTGRESQL_USERNAME'] %>
  POSTGRESQL_PASSWORD: <%= ENV['POSTGRESQL_PASSWORD'] %>

  # Devise
  ECOMMERCE_DEVISE_EMAIL: 'hello@gmail.com'

  # Facebook login
  ECOMMERCE_FACEBOOK_KEY: ''
  ECOMMERCE_FACEBOOK_SECRET: ''

  # Gmail
  # Make sure "access for less secure apps" is turned on in gmail
  # Used for:
  # - contact form (contact form emails get sent to ECOMMERCE_GMAIL_USERNAME)
  # - action mailer (email gets sent from ECOMMERCE_GMAIL_USERNAME)
  ECOMMERCE_GMAIL_USERNAME: 'hello@gmail.com'
  ECOMMERCE_GMAIL_PASSWORD: 'myPassword123'

  # Google Analytics
  ECOMMERCE_GOOGLE_ANALYTICS_CODE: 'UA-xxxxxxxx-x'

test:
  # PostgreSQL
  POSTGRESQL_USERNAME: <%= ENV['POSTGRESQL_USERNAME'] %>
  POSTGRESQL_PASSWORD: <%= ENV['POSTGRESQL_PASSWORD'] %>

production:
  ECOMMERCE_DEVISE_EMAIL: 'hello@gmail.com'
  ECOMMERCE_FACEBOOK_KEY: ''
  ECOMMERCE_FACEBOOK_SECRET: ''
  ECOMMERCE_GMAIL_USERNAME: 'hello@gmail.com'
  ECOMMERCE_GMAIL_PASSWORD: 'myPassword123'
  ECOMMERCE_GOOGLE_ANALYTICS_CODE: 'UA-xxxxxxxx-x'
